<table><tr><td><a href="https://mybinder.org/v2/gh/markcrowe-com/machine-learning/master?filepath=training-split.ipynb" target="_parent"><img src="https://mybinder.org/badge_logo.svg" alt="Open In Binder"/></a></td><td>online editors</td><td><a href="https://colab.research.google.com/github/markcrowe-com/machine-learning/blob/master/training-split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a></td></tr></table>

# Training

# Machine Learning
2. Data  
3. Split the data into groups: Train (75%) /Test (25%)
4. Linear regession train with train data
5. Linear regession to work on the test data


In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('Salary.csv')

In [29]:
dataset.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [10]:
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872, 127345, 126756,
       128765, 135675, 139465], dtype=int64)

In [22]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [23]:
(y_train)

array([ 37731,  55794, 112635, 105582, 139465, 128765, 116969, 127345,
        64445,  57081,  56642,  83088,  61111, 126756, 109431,  46205,
        56957,  60150, 113812,  39891,  81363,  98273,  93940,  57189,
        54445, 135675,  43525,  39343], dtype=int64)

In [25]:
# Training the Multiple Linear Regression model on the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)

#join columns
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Evaluating the Model Performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

[[120057.88 121872.  ]
 [ 88127.64  91738.  ]
 [ 73457.    66029.  ]
 [118331.92 122391.  ]
 [ 97620.42 101302.  ]
 [ 71731.04  67938.  ]
 [ 63101.25  63218.  ]]


0.9708090245443415

In [26]:
regressor.predict(X_test)

array([120057.88,  88127.64,  73457.  , 118331.92,  97620.42,  71731.04,
        63101.25])

In [27]:
y_test

array([121872,  91738,  66029, 122391, 101302,  67938,  63218],
      dtype=int64)